### PR TITLE
fix RngCore Sized

### PR DESCRIPTION
**Pull request by kigawas**
https://github.com/zkcrypto/ff/pull/14

### CODE REVIEW

**Comment by burdges** [comment]
`R: RngCore` should work fine because `impl<R> RngCore for &'a mut R where R: RngCore+?Sized` https://rust-random.github.io/rand/rand_core/trait.RngCore.html#foreign-impls  And similarly https://github.com/zkcrypto/ff/pull/14

**Comment by kigawas** [comment]
There's no reason using Sized here, I'm not a fan of implementing outside

**Comment by burdges** [comment]
An idiomatic usage would actually be this, although it might make error messages less clear and once I saw some other interaction, not sure all the consequences here.  https://github.com/rust-random/rand/issues/908
```
fn random<R: RngCore + ?Sized>(rng: R) -> Self {
```

**Comment by kigawas** [comment]
Yes. That's why we need this pr.

Using `?Sized` here enables us to make sure we are passing only one `Rng` instance from the top, especially it's easier to implement rand apis requiring `?Sized` (like `sample`)

**Comment by ebfull** [comment]
Sorry about the breakage.

**Comment by ebfull** [comment]
New versions of `pairing` / `ff` / `ff_derive` have been pushed to fix this.

**Comment by kigawas** [comment]
> New versions of `pairing` / `ff` / `ff_derive` have been pushed to fix this.

Can you take a look at this https://github.com/zkcrypto/group/pull/4 ?

**Pull request merged**
